#.·:·.《AUTOSTART.conf》.·:·..·:·..·:·..·:·.[05]-[01]-[025]
#   DESCRIPTION:
#   Programs to start on Startup
#
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ WAYBAR
#   ╚════════════☽【❖】☾═════════════╝
#
#   waybar:
    exec-once = waybar
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ PERIPHERY DRIVER
#   ╚════════════☽【❖】☾═════════════╝
#
#   ckb-next:
    exec-once = ckb-next
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ POLKIT
#   ╚════════════☽【❖】☾═════════════╝
#
#   polkit:
    exec-once = systemctl --user start polkit
#
#   hypr polkit agent:
    exec-once = systemctl --user start hyprpolkitagent
#
#   kde polkit agent:
    exec-once = /usr/lib/polkit-kde-authentication-agent-1
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ IDLING
#   ╚════════════☽【❖】☾═════════════╝
#
#   hypridle:
    exec-once = hypridle
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ NOTIFICATION CENTER
#   ╚════════════☽【❖】☾═════════════╝
#
#   sway notification center:
    exec-once = swaync
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ WALLPAPER
#   ╚════════════☽【❖】☾═════════════╝
#
#   hyprpaper:
    exec-once = hyprpaper
#
#
#
#   AUTHOR:
#   Liath
#
#.·:·.《✧》.·:·..·:·..·:·..·:·..·:·..·:·.《✧》.·:·.