#.·:·.《MONITORS.conf》.·:·..·:·..·:·..·:·.[05]-[01]-[025]
#   DESCRIPTION:
#   Configuration for monitors
#
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ MAIN MONITOR
#   ╚════════════☽【❖】☾═════════════╝
#
#   main monitor:
    monitor = HDMI-A-1,1920x1080,0x0,1
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ VERTICAL MONITOR
#   ╚════════════☽【❖】☾═════════════╝
#
#   vertical monitor:
    monitor = DP-2,1920x1080,1920x0,1,transform,1
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ THIRD MONITOR
#   ╚════════════☽【❖】☾═════════════╝
#
#   third monitor:
    monitor = DP-3,1920x1080,-1920x0,1
#
#
#
#   AUTHOR:
#   Liath
#
#.·:·.《✧》.·:·..·:·..·:·..·:·..·:·..·:·.《✧》.·:·.