#.·:·.《PROGRAMS.conf》.·:·..·:·..·:·..·:·.[05]-[01]-[025]
#   DESCRIPTION:
#   Default programs
#
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ TERMINAL
#   ╚════════════☽【❖】☾═════════════╝
#
#   kitty:
    $terminal = kitty
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ FILE EXPLORER
#   ╚════════════☽【❖】☾═════════════╝
#
#   dolphin:
    $fileManager = dolphin
#
#####   nemo:
####    $fileManager = nemo
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ PROGRAM MENU
#   ╚════════════☽【❖】☾═════════════╝
#
#   wofi:
    $programMenu = wofi --show drun -I
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ MUSIC PLAYER
#   ╚════════════☽【❖】☾═════════════╝
#
#   spotify:
    $musicPlayer = spotify-launcher
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ BROWSER
#   ╚════════════☽【❖】☾═════════════╝
#
#   firefox:
    $browser = firefox
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ DISCORD
#   ╚════════════☽【❖】☾═════════════╝
#
#   vesktop:
    $discord = vesktop
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ CALCULATOR
#   ╚════════════☽【❖】☾═════════════╝
#
#   gnome calculator:
    $calculator = gnome-calculator
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ CODE EDITOR
#   ╚════════════☽【❖】☾═════════════╝
#
#   vscodium:
    $codeEditor = vscodium
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ WALLPAPER MANAGER
#   ╚════════════☽【❖】☾═════════════╝
#
#   waypaper:
    $wallpaperManager = waypaper
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ KEYBOARD LAYOUT
#   ╚════════════☽【❖】☾═════════════╝
#
#   colemak:
    $keyboardLayout = colemak
#
#####   qwertz:
####    $keyboardLayout = us_US
#
#
#
#   AUTHOR:
#   Liath
#
#.·:·.《✧》.·:·..·:·..·:·..·:·..·:·..·:·.《✧》.·:·.