#.·:·.《WORKSPACE.conf》.·:·..·:·..·:·..·:·.[05]-[01]-[025]
#   DESCRIPTION:
#   Window rules for modified behavior
#
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ IGNORE MAXIMIZE REQUESTS
#   ╚════════════☽【❖】☾═════════════╝
#
#   ignore maximize request:
    windowrulev2 = suppressevent maximize, class:.*
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ FIX DRAGGING BUGS
#   ╚════════════☽【❖】☾═════════════╝
#
#   fix dragging bugs:
    windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ MAXIMISED MODIFIED COLOR
#   ╚════════════☽【❖】☾═════════════╝
#
#   maximised modified color:
    windowrulev2 = bordercolor rgb(ff0000) rgb(0000ff),fullscreen:1
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ OPAQUE FIREFOX
#   ╚════════════☽【❖】☾═════════════╝
#
#   opaque firefox:
    windowrule = opaque, title:(.*)(- YouTube)
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ OPACITY 1 FOR DISCORD
#   ╚════════════☽【❖】☾═════════════╝
#
#   opaque discord:
    windowrulev2 = opaque, class:$discord
#
#
#
#   ╔════════════☽【❖】☾═════════════╗
#   ║ OPACITY 1 FOR BROWSER
#   ╚════════════☽【❖】☾═════════════╝
#
#   opaque browser:
    windowrulev2 = opaque, class:$browser
#
#
#
#   AUTHOR:
#   Liath
#
#.·:·.《✧》.·:·..·:·..·:·..·:·..·:·..·:·.《✧》.·:·.